version: '3'
services:
  ohol:
    build: .
    image: ohol-server:latest
    ports:
      - '8005:8005'
    
    volumes:
      - './db:/opt/OneLife/server/db'
      - './settings:/opt/OneLife/server/settings'
